logging:
    level:
        'no':
            difi: INFO
        org: INFO

management:
    endpoints:
        web:
            base-path: /

'no':
    difi:
        statistics:
            elasticsearch:
                host: localhost
                port: 9200
                apikey: fake-secret

spring:
    jackson:
        default-property-inclusion: NON_EMPTY
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
